== Appendix 3

Appendix 3 Table S2. Examples of the texts used in the records reviewed
in which data generalization (DG) or data withheld (WH) were used to
describe data managements due to the potential sensitivity of the
species.

[width="100%",cols="9%,23%,29%,12%,12%,8%,7%",options="header",]
|===
|DWCA Term |Text |Comment |Publisher/institution |Species |IUCN
Conservation Category |Country of the occurrence
|DG |Geographic information generalized during aggregation due to the
sensitivity of the data to diffusion, according to SINP communication
rules |Many records are published following the same text-forma. Text
given in French and English |UMS PatriNat (OFB-CNRS- MNHN) |Tetrax
tetrax |NT |France

|DG |Location in England is already generalized to 0.01 degrees.
Sensitive in ENGLAND, Name: England, Zone: COUNTRY [Sensitive, Natural
England] |Many records are published following the same text-format, and
modifying the location, extent of generalization, area in which the
taxon is sensitive, and the reference (in this case Natural England)
|Biological Records Centre |Lutra lutra |NT |England

|DG |Record is Australia in Endangered. Generalized to 10km by Birds
Australia. |Many records are published following the same text-format,
and modifying the conservation category, extent of generalization and
the reference (in this case, Birds Australia) |NSW Bird Atlassers
|Dasyornis brachypterus |EN |Australia

|DG |Represents an endangered/threatened species. The specific locality
has been removed to protect this species from over-collection. These
data may be supplied to researchers on request | |Landcare Research
|Pittosporum patulum |EN |New Zealand

|WH |Coordinate uncertainty increased to 29330m to protect threatened
taxon |Many records are published following the same text-format, and
modifying the extent of generalization |iNaturalist* |Spiranthes
brevilabris |EN |USA

|WH |Geographic information generalized during aggregation at the
request of the producer |Many records are given with the similar text.
Text given in French and English |UMS PatriNat (OFB- CNRS-MNHN)
|Neophron percnopterus |EN |France

|WH |Coordinate uncertainty increased to 30003m to protect threatened
taxon |Many records are published following the same text-format, and
modifying the extent of generalization |iNaturalist* |Ceratotherium
simum |NT |South Africa

|WH |Coordinate uncertainty increased to 30699m to protect threatened
taxon |Many records are published following the same text-format, and
modifying the extent of generalization |iNaturalist* |Ceratotherium
simum |NT |Zimbabue
|===

*As observed, iNaturalist used both WH and DG to describe sensitivity.
