// add cover image to img directory and update filename below
ifdef::backend-html5[]
image::[]
endif::backend-html5[]

== Colophon

=== Suggested citation

Astorga F, Rodrigues A & Waller J (2024) Exploring the risk and benefits of publishing sensitive species data. GBIF Secretariat: Copenhagen. 
// Uncomment once a DOI is assigned
//https://doi.org/10.EXAMPLE/EXAMPLE

=== Authors

https://orcid.org/0000-0002-7108-6919[Francisca Astorga^], https://orcid.org/0000-0002-5468-2452[Andrew Rodrigues^] & https://orcid.org/0000-0002-7302-5976[John Waller^]

=== Contributors

Name as needed/desired

=== Licence

The document _Exploring the risk and benefits of publishing sensitive species data_ is licensed under https://creativecommons.org/licenses/by-sa/4.0[Creative Commons Attribution-ShareAlike 4.0 Unported License].

=== Persistent URI

#TODO: Assign a DOI before publication#
// Uncomment once a DOI is assigned
//https://doi.org/10.EXAMPLE/EXAMPLE

=== Document control

First final edition, February 2024

// include reference to provenance if possible/relevant
https://doi.org/10.EXAMPLE/2ND-EXAMPLE[Second edition], March 2015, by Due Autore and https://orcid.org/0000-0000-0000-0000[Troisième Auteur].

=== Cover image

// Caption. Credit, source, licence.
