== Executive Summary and Recommendations

This report provides an overview of existing frameworks for identifying and generalizing sensitive species data and explores the utility of the global https://www.iucnredlist.org/[IUCN Red List of Threatened Species(TM)^] and https://cites.org/eng/app/index.php[CITES Appendix lists^] for identifying sensitivity in the data. Where we know there are sensitivities within the data, GBIF-mediated data were assessed to evaluate the degree to which data publishers are generalizing those data.

The report identifies a range of well-developed protocols at both national, through GBIF nodes, and organizational levels for identifying and generalizing sensitive species. Similar protocols do not appear to exist for the majority of GBIF´s data publishing community, and there is an opportunity for GBIF to share best practices more widely within its community. While it is tempting to use global lists such the IUCN Red List and CITES to define sensitivity within the data, these global lists fail to capture sensitivities at more local levels, and using these global proxies may over- or undergeneralize the data, which would affect both local reuse and global security concerns. National and regional approaches are encouraged in developing sensitive species data frameworks.

The majority of species considered sensitive do not have fully generalized occurrence data, i.e. a proportion of occurrences for these species will not be generalized. However, occurrence generalization rates tend to be higher for records of species considered as sensitive compared with those that are not, and even higher for repatriated records for species in countries in which they are listed on those national sensitive species lists. Where they have been generalized, data are inconsistently generalized between data publishers and the sensitivity within the data is inconsistently flagged across datasets, as can be observed for two well-known sensitive taxa: rhinos (Rhinocertidae) and orchids (Orchidaceae). More support needs to be provided to data publishers to ensure future reusability of the data through richer dataset metadata, fixed vocabularies for those terms commonly used for data generalization and training support for data publishers on best practices for data generalization.

It is important to state that with regard to the handling of sensitive species data, GBIF is ahead of other biodiversity data platforms, most notably compared to social media, which may not have guidelines or generalization protocols in place for sensitive species data. Even with these relatively well-developed guidelines in place, we would encourage the use of generalizations as an exception to the rule to ensure that data remain as informative as possible for future reuse in research and conservation.
