== Executive Summary and Recommendations

This report provides an overview of existing frameworks for identifying and generalizing sensitive species data and explores the utility of the global https://www.iucnredlist.org/[IUCN Red List of Threatened Species(TM)^] and https://cites.org/eng/app/index.php[CITES Appendices^] for identifying sensitivity in the data. Where known sensitivities exist within the data, we assessed GBIF-mediated data to evaluate the degree to which publishers are generalizing those data.

The report identifies a range of well-developed protocols at national (through GBIF nodes) and organizational levels for identifying and generalizing sensitive species. However, most GBIF´s data publishing community does not appear to use such protocols, and this report provides an opportunity to share best practices more widely within the GBIF community. While it is tempting to rely on global lists such the IUCN Red List and CITES to define sensitivity within the data, these global lists fail to capture sensitivities at more local levels, and using these global proxies may over- or undergeneralize the data, which would affect both local reuse and global security concerns. As a result, we encourage national and regional approaches for developing sensitive species data frameworks.

The majority of species considered sensitive do not have fully generalized occurrence data, i.e. a proportion of occurrences for these species will not be generalized. However, occurrence generalization rates tend to be higher for records of species considered as sensitive compared with those that are not, and even higher for repatriated records for species in countries in which they are listed on those national sensitive species lists. Where it has been generalized, data is inconsistently generalized between data publishers, and the sensitivity within the data is inconsistently flagged across datasets. In this report, we observe this phenomenon using two well-known sensitive taxa: rhinos (Rhinocertidae) and orchids (Orchidaceae). Data publishers need more support to ensure future reusability of the data through richer dataset metadata, fixed vocabularies for those terms commonly used for data generalization, and training on best practices for data generalization.

It is important to note that, despite these challenges and limitations, GBIF is ahead of other biodiversity data platforms with regard to the handling of sensitive species data, most notably compared to social media, which may not have guidelines or generalization protocols in place for sensitive species data. Even with these relatively well-developed guidelines in place, we would encourage the use of generalization as an exception to the rule to ensure that data remain as broadly informative as possible for future reuse in research and conservation.
