== Introduction

GBIF provides more than 2 billion occurrence records from thousands of data publishing institutions worldwide, and the data are freely and openly reused in a range of science and policy applications (https://doi.org/10.1177/0309132516646641[Adams (2017)^]; https://doi.org/10.1590/0001-3765202220211043[Angarita-Sierra et al. (2022)^]; (#arino[Ariño 2014]); https://doi.org/10.1016/j.onehlt.2023.100484[Astorga F et al. (2023)^], https://doi.org/10.1371/journal.pone.0215794[Ball-Damerow et al. (2019)^], https://doi.org/10.1038/s42003-022-03638-9[Borgelt J et al. (2022)^];(#chapman[Chapman 2006]); (#chapman[Chapman 2020]);https://doi.org/10.2903/sp.efsa.2022.EN-7667[ENETWILD consortium et al. (2022)^]; https://doi.org/10.1016/j.antiviral.2014.05.016[Estrada-Peña A & de la Fuente J (2014)^]; https://doi.org/10.1073/pnas.2018093118[Heberling et al. (2021)^]; https://doi.org/10.1002/ajp.23213[Heinicke et al. (2021)^]; https://doi.org/10.1016/j.tree.2011.11.006[Hochachka et al. (2012)^]; https://doi.org/10.1525/bio.2009.59.7.12[Kelling et al. (2009)^];(#Lindenmayer & Scheele [Lindenmayer & Scheele 2017]);https://doi.org/10.1111/bij.12517[Powney & Isaac (2015)^];https://doi.org/10.1111/ddi.13068[Robinson et al (2020)^];(#Saarenmaa [Saarenmaa 2005]);https://doi.org/10.1098/rstb.2003.1439[Soberón & Peterson (2004)^];https://doi.org/10.1007/s10651-021-00508-1[Tang(2021)^];https://doi.org/10.1128/mBio.02698-20[Thompson et al. (2021)^];https://doi.org/10.1371/journal.pbio.1001220[Wood et al. (2011)^];https://doi.org/10.1016/j.biocon.2019.03.029 [Xing et al. (2019)^]). This data can be sensitive in nature, revealing localities of species that could increase threats to individuals or populations. In recognition of this, GBIF provides robust documentation - the guide to best practices for generalizing sensitive data (#chapman[Chapman 2020]) - to assist data publishers to generalize their data in a way that is consistent with the principles of open data.

Despite these active efforts by GBIF to provide guidance and standardize the process for generalizing sensitive data, concerns are still regularly raised about the possible availability of sensitive data. In parallel, there is an increasing awareness at a national level of the importance of restricting access to some sensitive data. Finding the balance between free and open data at resolutions that are useful for answering scientific questions and generalizing or restricting data for reuse to ensure that data is not used for nefarious purposes is a challenge https://support.ebird.org/en/support/solutions/articles/48000803210-sensitive-species-in-ebird#How-should-eBirders-report-sensitive-species?-[Contreras-Díaz R G et al. (2023)^].

In this report, we investigated existing approaches for identifying sensitive species data and examined how sensitive data within GBIF is currently being managed, with a view of identifying best practices within the GBIF community. Based on these findings, we explored potential improvements that can be made within the data publishing workflow to facilitate the publication and reuse of sensitive species data to ensure that data are as precise as possible, and as generalized as needed.

*_Sensitive species_* are defined in this report as taxa potentially threatened by targeted use e.g. hunting, collection, pet trade, or through human disturbance e.g. wildlife watching. *_Sensitive species data_* is defined here as any _data_ which, if released to the public, could potentially result in adverse effects on the populations or individuals of sensitive species. We have not focused on other potential reasons for sensitivity within the data, including biosecurity and traditional knowledge, while understanding that these factors should be considered in future discussions on sensitive data. The acquisition of data for all analyses was completed in January 2023.
