== References

Adams WM (2017) Geographies of conservation I: De-extinction and precision conservation. Progress in Human Geography 41(4): 534–545. https://doi.org/10.1177/0309132516646641 

ALA (2018) What is Sensitive Data? Atlas of Living Australia. https://lists.ala.org.au/public/speciesLists?isSDS=eq%3Atrue

Angarita-Sierra T, Montaño-Londoño LF & Bravo-Vega CA (2022) ID please: Evaluating the utility of Facebook as a source of data for snake research and conservation. Anais Da Academia Brasileira de Ciências 94(suppl.3): e20211043. https://doi.org/10.1590/0001-3765202220211043

[[arino]]Ariño AH (2014) Filling Biodiversity Knowledge Gaps: GBIF supporting research for conservation management. GB21: the 21st meeting of the GBIF Governing Board. Copenhagen: GBIF Secretariat. https://www.gbif.org/sites/default/files/gbif_resource/resource-80932/AArino-Filling-Biodiversity-Knowledge-Gaps.pptx.pdf

Astorga F, Groom Q, Shimabukuro PHF, Manguin S, Noesgaard D, Orrell T, Sinka M, Hirsch T & Schigel D (2023) Biodiversity data supports research on human infectious diseases: Global trends, challenges, and opportunities. One Health 16: 100484. https://doi.org/10.1016/j.onehlt.2023.100484

Auliya M, Altherr S, Ariano-Sanchez D, Baard EH, Brown C, Brown RM et al. (2016) Trade in live reptiles, its impact on wild populations, and the role of the European market. Biological Conservation 204: 103–119. https://doi.org/10.1016/j.biocon.2016.05.017

Bailey LL, Simons TR, & Pollock KH (2004) Estimating detection probability parameters for Plethodon salamanders using the robust capture–recapture design. Journal of Wildlife Management 68(1): 1–13. link:++https://doi.org/10.2193/0022-541X(2004)068[0001:EDPPFP]2.0.CO;2++[]

Ball-Damerow JE, Brenskelle L, Barve N, Soltis P S, Sierwald P, Bieler R, LaFrance R, Ariño A H, Guralnick R P (2019) Research applications of primary biodiversity databases in the digital age. PLOS ONE 14(9): e0215794. https://doi.org/10.1371/journal.pone.0215794

Bloom DA, Wieczorek JR & Zermoglio PF (2020) Georeferencing Calculator Manual. Copenhagen: GBIF Secretariat. https://doi.org/10.35035/gdwq-3v93

Borgelt J, Dorber M, Høiberg M A & Verones F (2022) More than half of data deficient species predicted to be threatened by extinction. Communications Biology 5(1): 679. https://doi.org/10.1038/s42003-022-03638-9

Bosman A, Steyns H, Muller B & Steenkamp C (2021) NSCF Georeferencing protocol v2.0. Natural Sciene Collections Facility. https://tdwg.github.io/esp/georeferencing/workflows/NSCF-Georeferencing-protocol.pdf

Boyd C, Brooks TM, Butchart SHM, Edgar GJ, Da Fonseca GAB, Hawkins F, Hoffmann M, Sechrest W, Stuart SN & Van Dijk PP (2008) Spatial scale and the conservation of threatened species: Spatial scale and the conservation of threatened species. Conservation Letters 1(1): 37–43. https://doi.org/10.1111/j.1755-263X.2008.00002.x

Chapman AD (2006) Questionnaire on Dealing with Sensitive Primary Species Occurrence Data Summary of Reponses. Copenhagen: GBIF Secretariat. https://doi.org/10.35035/vs84-0p13

Chapman AD (2020) Current Best Practices for Generalizing Sensitive Species Occurrence Data. Copenhagen: GBIF Secretariat. https://doi.org/10.15468/doc-5jp4-5g10

Chapman AD & Wieczorek JR (2020) Georeferencing Best Practices. Copenhagen: Copenhagen: GBIF Secretariat. https://doi.org/10.15468/doc-gg7h-s853

Contreras-Díaz RG, Nori J, Chiappa-Carrara X, Peterson TA, Soberón J & Osorio-Olvera J (2023) Well-intentioned initiatives hinder understanding biodiversity conservation: Cloaked iNaturalist information for threatened species. Biological Conservation 282: 110042. https://doi.org/10.1016/j.biocon.2023.110042

eBird (2023) Sensitive Species in eBird. eBird Help Center. https://support.ebird.org/en/support/solutions/articles/48000803210-sensitive-species-in-ebird#How-should-eBirders-report-sensitive-species?-

Efford MG & Schofield MR (2022) A review of movement models in open population capture–recapture. Methods in Ecology and Evolution 13(10): 2106–2118. https://doi.org/10.1111/2041-210X.13947

ENETWILD consortium, Jaroszynska F, Body G, Pamerlon S & Archambeau A. (2022) Applying the Darwin Core data standard to wildlife disease – advancements toward a new data model. EFSA Supporting Publications 19(11): EN-7667E. https://doi.org/10.2903/sp.efsa.2022.EN-7667

Estrada-Peña A & de la Fuente J. (2014) The ecology of ticks and epidemiology of tick-borne viral diseases. Antiviral Research 108: 104–128. https://doi.org/10.1016/j.antiviral.2014.05.016

Fay MF (2018) Orchid conservation: How can we meet the challenges in the twenty-first century? Botanical Studies: 59(1): 16. https://doi.org/10.1186/s40529-018-0232-z

GBIF.org (2023) GBIF Occurrence Download https://doi.org/10.15468/dl.gvxuzs 

GBIF.org (2022a) GBIF Occurrence Download. https://doi.org/10.15468/dl.yyw5pj

GBIF.org (2022b) GBIF Occurrence Download. https://doi.org/10.15468/dl.kbwbf3

GEF Montaña (2018) Monitoreo de fauna nativa del GEF montaña registra presencia inédita de gato andino en el Cajón del Maipo. Noticias SIMBIO. https://gefmontana.mma.gob.cl/monitoreo-de-fauna-nativa-del-gef-montana-registra-presencia-inedita-de-gato-andino-en-el-cajon-del-maipo/

Glaser A (2019) Plants and Birds Need Privacy Online, Too. Slate, 4 April 2019. https://slate.com/technology/2019/04/superbloom-california-nature-internet-collide-birds-poaching-science.html

Heberling JM, Miller JT, Noesgaard D, Weingart SB & Schigel D (2021) Data integration enables global biodiversity synthesis. Proceedings of the National Academy of Sciences 118(6): e2018093118. https://doi.org/10.1073/pnas.2018093118

Heinicke S, Ordaz‐Németh I, Junker J, Bachmann ME, Marrocoli S, Wessling EG et al. (2021) Open‐access platform to synthesize knowledge of ape conservation across sites. American Journal of Primatology 83(1): e23213. https://doi.org/10.1002/ajp.23213

Hinsley A, de Boer H , Fay MF, Gale SW, Gardiner LM, Gunasekara RS, Kumar P, Masters S, Metusala D, Roberts DL, Veldman S, Wong S, Phelps J. (2018) A review of the trade in orchids and its implications for conservation. Botanical Journal of the Linnean Society 186(4): 435–455. https://doi.org/10.1093/botlinnean/box083

Hinsley A, Lee TE, Harrison JR & Roberts DL (2016) Estimating the extent and structure of trade in horticultural orchids via social media: Social-Media Orchid-Trade Networks. Conservation Biology 30(5): 1038–1047. https://doi.org/10.1111/cobi.12721

Hochachka WM, Fink D, Hutchinson RA, Sheldon D, Wong W-K & Kelling S. (2012) Data-intensive science applied to broad-scale citizen science. Trends in Ecology & Evolution, 27(2), 130–137. https://doi.org/10.1016/j.tree.2011.11.006

Howe EJ, Potter D, Beauclerc KB, Jackson KE & Northrup, JM (2022) Estimating animal abundance at multiple scales by spatially explicit capture–recapture. Ecological Applications 32(7): ee2638. https://doi.org/10.1002/eap.2638

Ichter J, Robert S & Touroult J (2022) Sensibilité des données à la diffusion. Guide technique du SINP. v2.0. Paris: Muséum national d'Histoire naturelle. https://inpn.mnhn.fr/docs-web/docs/download/404525

iNaturalist (2022) Obscuring Sensitive Species Data. https://www.inaturalist.org/projects/hdms-point-observation-database/journal/9042-obscuring-sensitive-species-data

iNaturalist (2023) Frequently Asked Questions: What is geoprivacy? What does it mean for an observation to be obscured? https://www.inaturalist.org/pages/help#geoprivacy

IUCN (2022) Threats Classification Scheme (Version 3.2) https://www.iucnredlist.org/resources/threat-classification-scheme

Kelling S, Hochachka WM, Fink D, Riedewald M, Caruana R, Ballard G & Hooker G (2009) Data-intensive Science: A New Paradigm for Biodiversity Studies. BioScience 59(7): 613–620. https://doi.org/10.1525/bio.2009.59.7.12

Kéry M & Schmid H (2004) Monitoring programs need to take into account imperfect species detectability. Basic and Applied Ecology 5(1): 65–73. https://doi.org/10.1078/1439-1791-00194

Lindenmayer D & Scheele B (2017) Do not publish: Limit open access information on rare and endangered species. Science 356(6340): 800-801. https://doi.org/10.1126/science.aan1362

NBN (2019) Sensitive Data. National Biodiversity Network. https://nbn.org.uk/sensitive-data/

NSW (2006) Sensitive Species Data Policy. Department of Environment, Climate Change and Water (DECCW), New South Wales. `CHECK TO SEE IF THIS IS THE SAME AS` DECCW (2009) Sensitive Species Data Policy. New South Wales Department of Environment, Climate Change and Water. https://www.environment.nsw.gov.au/resources/nature/SensitiveSpeciesPolicyDEC09.pdf

Powney GD & Isaac NJB (2015) Beyond maps: A review of the applications of biological records: Applications of Biological Records. Biological Journal of the Linnean Society 115(3): 532–542. https://doi.org/10.1111/bij.12517

Robinson OJ, Ruiz‐Gutierrez Viviana, Reynolds MD, Golet GH, Strimas‐Mackey M & Fink D. (2020) Integrating citizen science data with expert surveys increases accuracy and spatial extent of species distribution models. Diversity and Distributions 26(8): 976–986. https://doi.org/10.1111/ddi.13068

Saarenmaa H (2005) Sharing and Accessing Biodiversity Data Globally through GBIF.

SANBI (2010) Biodiversity Information Policy Framework: Principles and Guidelines, Policy Series. Pretoria, South Africa: South African National Biodiversity Institute. http://hdl.handle.net/20.500.12143/7450

SANBI (2016) Report of the National Sensitive Species List Workshop: 18 and 19 August 2016. Pretoria, South Africa: South African National Biodiversity Institute. http://hdl.handle.net/20.500.12143/7451

SANBI (2018) National Sensitive Species List (NSSL) of 2018: Summary of changes. Version 1.0. South African National Biodiversity Institute (SANBI). http://nssl.sanbi.org.za/

Schlaepfer MA, Hoover C & Dodd CK (2005) Challenges in Evaluating the Impact of the Trade in Amphibians and Reptiles on Wild Populations. BioScience 55(3):256. link:++https://doi.org/10.1641/0006-3568(2005)055[0256:CIETIO]2.0.CO;2++[]

Siler CD, Linkem CW, Cobb K, Watters JL, Cummings ST, Diesmos AC & Brown RM (2014) Taxonomic revision of the semi-aquatic skink Parvoscincus leucospilos (Reptilia: Squamata:Scincidae), with description of three new species. Zootaxa 3847(3):388. https://doi.org/10.11646/zootaxa.3847.3.4

SINP (2017) Protocole du Système d´Information sur la Nature et les Paysages. Paris: Système d´Information sur la Nature et les Paysages. https://abc.naturefrance.fr/documents/protocole-du-systeme-dinformation-sur-la-nature-et-les-paysages

SLU Artdatabanken (2020) List of sensitive species nationally protected in Sweden. SLU Artdatabanken https://doi.org/10.15468/JWBTSB

Soberón J & Peterson T (2004) Biodiversity informatics: Managing and applying primary biodiversity data. Philosophical Transactions of the Royal Society of London. Series B: Biological Sciences 359(1444): 689–698. https://doi.org/10.1098/rstb.2003.1439

Tang B, Clark JS & Gelfand AE (2021) Modeling spatially biased citizen science effort through the eBird database. Environmental and Ecological Statistics 28(3): 609–630. https://doi.org/10.1007/s10651-021-00508-1

Theng M, Milleret C, Bracis C, Cassey P & Delean S (2022) Confronting spatial capture–recapture models with realistic animal movement simulations. Ecology 103(10): e3676. https://doi.org/10.1002/ecy.3676

Thompson CW, Phelps KL, Allard MW, Cook JA, Dunnum J L, Ferguson AW et al. (2021) Preserve a Voucher Specimen! The Critical Need for Integrating Natural History Collections in Infectious Disease Studies. MBio 12(1): e02698-20. https://doi.org/10.1128/mBio.02698-20

Tourani M (2022) A review of spatial capture–recapture: Ecological insights, limitations, and prospects. Ecology and Evolution 12(1): e8468. https://doi.org/10.1002/ece3.8468

Touroult J, Birard J, Bouix T, Chataigner J, De Wever P, Gourvil J et al. (2014) Définition et gestion des données sensibles sur la nature dans le cadre du SINP. Guide technique. Rapport pour le SINP, rapport MNHN‐SPN 2014‐27 https://inpn.mnhn.fr/docs/SINP/sinp_guide_technique_donnees_sensible_v1_avril_2014.pdf

Wieczorek J, Guo Q & Hijmans R (2004) The point-radius method for georeferencing locality descriptions and calculating associated uncertainty. International Journal of Geographical Information Science 18(8): 745–767. https://doi.org/10.1080/13658810412331280211

Wood C, Sullivan B, Iliff M, Fink D & Kelling S (2011) eBird: Engaging Birders in Science and Conservation. PLoS Biology 9(12): e1001220. https://doi.org/10.1371/journal.pbio.1001220

Xing S, Au TF, Dufour PC, Cheng W, Landry Yuan F, Jia F, V, LV, Wang M & Bonebrake TC (2019) Conservation of data deficient species under multiple threats: Lessons from an iconic tropical butterfly (_Teinopalpus aureus_) Biological Conservation 234:154–164. https://doi.org/10.1016/j.biocon.2019.03.029
